### ISSUE TITLE
Add translations for toc-title/chapter-label

### ISSUE THREAD

**Issue by jfiala** [Swagger2Markup/swagger2markup#161]
To allow to translate the generated asciidoctor-files completely, this should be added to the project-template or in the documentation:

index.adoc:
// Translate TOC-title (DE)
:toc-title: Inhaltverzeichnis

// Translate Chapter-Label (DE)
:chapter-label: Kapitel

Pls let me know where this should be added?
Or should there be a index_de.adoc which includes the sample for translating to german?

**Comment by Kabhal** [comment]
Some thoughts :
1. This requirement should only appear when you use the Swagger2MarkupConverter::toFile() method and expect the generated file to be the final AsciiDoc document, because other modes (toFolder()) expect you later include generated files into an existing document. 
2. There are many more attributes you could want to add to AsciiDoc document.
3. These attributes responsability is IMHO out of Swagger2Markup scope
4.  You can add some attributes later at HTML generation (asciidoctor -a)

**Comment by jfiala** [comment]
ad 1.) I'm using the Swagger2Markup maven plugin (see swagger2markup-maven-project-template).
Maybe it would make sense adding it there, additionally to the language parameter which isn't mentioned there yet:
<swagger2markup.outputLanguage>DE</swagger2markup.outputLanguage>

Especially users using the outputLanguage might wonder why there is still english text appearing (as I did...), resulting in unnecessary confusion.

ad 2/3/4/5/6: OK :)

**Comment by Kabhal** [comment]
@RobWin ?

**Comment by RobWin** [comment]
In order to customize Asciidoctor built-in labels, you either customizer the build script (build.gradle or pom.xml) or the index.adoc.

You can clone the swagger2markup-maven-project-template and customize it to your needs.

**Comment by jfiala** [comment]
@RobWin Thank you, I already did that for my project. The question was if it makes sense to add samples for translating to e.g. german to the swagger2markup-maven-project-template, so users see how to get a fully translated html/pdf...
