### ISSUE TITLE
Descriptions are treated as AsciiDoc?

### ISSUE THREAD

**Issue by yewton** [Swagger2Markup/swagger2markup#43]
Hi,

Swagger spec says that some descriptions can be written in GFM syntax.
swagger2markup seems to preserve those descriptions as-is, so they are broken as AsciiDoc.
I hope that swagger2markup will covert descriptions from GFM to AsciiDoc.

Example input: http://petstore.swagger.io/v2/swagger.json

Thanks.

**Comment by RobWin** [comment]
Hi, yes. Thats in my to-do list. I have to search for a good GFM to AsciiDoc converter.

If you use Swagger2markup and like it, I would love to get your GitHub Star.

**Comment by yewton** [comment]
Starred :star:  Thanks :heart:

**Comment by RobWin** [comment]
For reference:
I can use the following library to convert Markdown into AsciiDoc:
https://github.com/bodiam/markdown-to-asciidoc

**Comment by Kabhal** [comment]
Whatever you do, it would be cool to keep an option to support AsciiDoc in descriptions as currently ;)

**Comment by ruisalgado** [comment]
This is also a must have for my use case - wherein swagger is used in a contract-first approach and edited with the online [swagger editor](http://editor.swagger.io/#/), which does support GFM. 

Have you managed to put some work into this already? Even if it's just work-in-progress. Would love to be able to use the tool.

**Comment by RobWin** [comment]
No, not yet. 
And I won't have time for this feature in the near future.
Feel free to create a PR. There is a library to convert Markdown to AsciiDoc which can be used to convert the Markdown descriptions into AsciiDoc.

https://github.com/bodiam/markdown-to-asciidoc

**Comment by Kabhal** [comment]
Fixed in https://github.com/Swagger2Markup/swagger2markup/tree/23331930cceabc4e0cb48800067a0877230188b3
Introduced new S2M configuration option .withSwaggerMarkupLanguage().
A conversion from 'withSwaggerMarkupLanguage' to target language is applied to the following Swagger descriptions :
- Overview/SecurityScheme descriptions
- Paths descriptions
- Definitions descriptions
- Properties/parameters/responses descriptions

Other Swagger fields are not converted.

By default, Swagger markup language is Markdown (/!\ S2M Markdown flavor is GFM).

The conversions currently supported are :
- Markdown -> AsciiDoc
