### ISSUE TITLE
Definitions links in generated markup

### ISSUE THREAD

**Issue by Kabhal** [Swagger2Markup/swagger2markup#50]
Hello,

When I generate Markdown or AsciiDoc from a swagger spec file, no links are generated to directly go to the definitions from paths parameters or responses.

However it seems these links exists when using the spring-swagger2markup-demo (generating HTML from code).
What am i missing ?

**Comment by RobWin** [comment]
Links are only working with AsciiDoc.
Did you create an index.adoc file?

**Comment by RobWin** [comment]
Btw. If you like Swagger2markup, I would love to get your GitHub Star

**Comment by Kabhal** [comment]
Links does not appear in generated markup, whatever the output format (asciidoc or md).
So you mean links are added later in the process, when using asciidoctor (via  asciidoctor-maven-plugin for example) to generate HTML or PDF ?

**Comment by Kabhal** [comment]
ok, I should have read the asciidoc spec, the <<Type>> are anchors, so it should work for AsciiDoc.
Is it possible to support links in Markdown too ? :)

**Comment by RobWin** [comment]
Yes, but I dont know how to do it in Markdown :(
The links in AsciiDoc only work if you combine (include) all documents in an index.adoc an generate HTML or PDF from that index file.

**Comment by Kabhal** [comment]
What about a new output mode to generate a all-in-one page for Markdown or all languages ?
Then you could support the links for Markdown in this mode only.

**Comment by dodev** [comment]
Hey guys!

I've been trying out swagger2markup the last few days for auto-generating our micro services' documentation. We use markdown because our documentation indexing can easily process it.

So I have to give my +1 for markdown schema definition links, because without it the docs feel incomplete. And therefore +1 for generating a single markdown file.

**Comment by RobWin** [comment]
If you invoke asString instead of intoFolder, you get the docs as a string which you can save into a single file.

**Comment by RobWin** [comment]
How do you create links/references in Markdown?

**Comment by Kabhal** [comment]
Woa, it seems Markdown does not support cross-references, so you have to use some HTML :)
Best answer so far : http://stackoverflow.com/questions/5319754/cross-reference-named-anchor-in-markdown/7335259#7335259

**Comment by RobWin** [comment]
Yes. That's why I haven't implemented it.

**Comment by Kabhal** [comment]
Anyway, HTML is the main (only ?) Markdown rendering format, so I guess it's not a problem ...

**Comment by Kabhal** [comment]
> If you invoke asString instead of intoFolder, you get the docs as a string which you can save into a single file.

I'm using swagger2markup-cli ;)

**Comment by RobWin** [comment]
Why ? ;)

**Comment by dodev** [comment]
> How do you create links/references in Markdown?
Good question. I've always took the header anchors in markdown for granted and thought they were  part of [Markdown's header syntax spec ](http://daringfireball.net/projects/markdown/syntax#header).

Turns out that the spec doesn't say anything about internal document anchors. It's a [Github Markdown renderer feature](https://gist.github.com/asabaylus/3071099). 

Anyway cross-linking increases the usability of the output documentation and many folk would find that as plus. So my +1 remains for links for definitions in markdown.

**Comment by RobWin** [comment]
Implemented in release v0.10.0
