### ISSUE TITLE
Support for vendor extensions

### ISSUE THREAD

**Issue by mrpotes** [Swagger2Markup/swagger2markup#75]
Hello, sorry if I've missed where this is answered in your docs and/or other issues. What support is there for vendor extensions (properties prefixed `x-`) in the swagger definition docs? 

If none, is there any plan to add support? 

Is this something you would accept contributions for?

**Comment by RobWin** [comment]
Hello, 
currently there is no support for vendor extensions, but this is just because there was no request for it yet.
I'm happy about every contribution. The source code should not be too complicated to add it. If you have question, just join the Gitter Chat https://gitter.im/Swagger2Markup/swagger2markup.

If you like Slack more, I can also invite you to the Slack chat room, but then I need an E-Mail Address. You give it in a private Gitter chat, if you like.

**Comment by RobWin** [comment]
Every contribution costs a GitHub star :P :P

**Comment by RobWin** [comment]
Vendor Extensions can be implemented with the Swagger2Markup Extension SPI of the upcoming v1.0.0

**Comment by RobWin** [comment]
@mrpotes Do you want to test the Extension SPI to implement your needs?
See Extension SPI documentation of the upcoming version.
 http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT/

If you need help, please join the Gitter channel.
